### PR TITLE
Null Drink Name Fix

### PR DESCRIPTION
**Pull request by pitaden**
## Description of changes
Fixes the null name bug on drinks via upstream, and lets a few drink containers show their contents

## Why and what will this PR improve
Having a smaller number of bugs is nice, as well as properly listing what's in vending machines

## Authorship
pitaden (after being conscripted by genessee)

## Changelog
:cl:
bugfix: fixed invisible/non-descriptive drink names
/:cl:

### CODE REVIEW

**Comment by genessee-forgot-his-password-again** [comment]
Ran it on a test server. It works!

**Comment by PsyCommando** [comment]
Pretty sure that's been fixed upstream. Might be worth to take a look.

**Comment by pitaden** [comment]
Guh! Checking upstream, it has indeed been fixed there, and as a much easier fix: moving `. = ..()` to the end of `get_base_name`

**Comment by PsyCommando** [comment]
We've pulled that fix by now pretty sure. So going to close this.

**Pull request closed without merging**
