### PR TITLE
camera/memory mods

### PR DESCRIPTION
**Pull request by Tetsukiba**
Plug and play mod. Files added are named exactly the same as the original file. Just enable new files and disable the original. Use search input (Bottom Left) to find the original. Also added some copied template files. (didn't want to completely change original and left it to the developers to implement) I did change the scanner.tmpl file, the text was changed because it didn't wrap well in game.

### CODE REVIEW

**Comment by NataKilar** [comment]
Hi Tetsu, thank you for your PR. I'll look over this in more detail soon, but before I do, I wanted to make note of something regarding the modpack usage. When using modpacks, you shouldn't be completely replacing the files in the "base game", but instead only overriding what you need to and leaving other things be. You can look at other examples in the persistence modpack for an idea how to do this, _network_machine.dm for instance. As you can see, things like name, icon definitions, and variable definitions are left generally untouched, and only necessary changes are made. In a mod pack, you can use in a proc . = ..() to call the proc as it would have been defined in the 'base game'.

This is a somewhat complicated topic and I understand if this doesn't quite clarify things. Feel free to ping me on Discord and I can help you out if needed.

**Comment by Tetsukiba** [comment]
> Hi Tetsu, thank you for your PR. I'll look over this in more detail soon, but before I do, I wanted to make note of something regarding the modpack usage. When using modpacks, you shouldn't be completely replacing the files in the "base game", but instead only overriding what you need to and leaving other things be. You can look at other examples in the persistence modpack for an idea how to do this, _network_machine.dm for instance. As you can see, things like name, icon definitions, and variable definitions are left generally untouched, and only necessary changes are made. In a mod pack, you can use in a proc . = ..() to call the proc as it would have been defined in the 'base game'.
> 
> This is a somewhat complicated topic and I understand if this doesn't quite clarify things. Feel free to ping me on Discord and I can help you out if needed.

Made changes to reduce unnecessary code. 
The files:
/mods/persistence/game/machinery/camera.dm
/mods/persistence/game/machinery/camera_assembly.dm
/mods/persistence/modules/modular_computers/file_system/programs/camera.dm

Can't be implemented without changing core code to my knowledge. If you see that they can, please provide more insight.
#98

**Comment by Andrew-Fall** [comment]
This is three different unrelated things bundled in one. They should be split up into separate PRs. They should also probably be done upstream.

**Comment by Tetsukiba** [comment]
> This is three different unrelated things bundled in one. They should be split up into separate PRs. They should also probably be done upstream.

Are you sure they should be done upstream? Wouldn't that be nebula code? Also yes they are bundled, however they're all mods, still waiting on information on what to do about the three files that require core changes.

**Pull request closed without merging**
