### PR TITLE
Network fixes and additions

### PR DESCRIPTION
**Pull request by NataKilar**
## Description of changes
Various network fixes and additions.
* Adds network lockable extension for objects to copy network lock access without having a network device extension themselves
* Adds network lockable crates and closets, producible in the industrial fabricator
* Allows network locks to add individual account accesses to access patterns. Removes default behavior setting, replaces it with a toggle whether or not to require network connection to function
* Makes network ID cards temporarily cache their access on connection (currently 30 minutes), so all access is not lost in the event of a network outage.
* A runtime fixe with network money accounts

## Authorship
Myself

### CODE REVIEW

**Comment by PsyCommando** [comment]
Psst, you forgot to add changelogs for the lockers stuff?

**Review by PsyCommando — APPROVED** [review]
I'll approve, but I'm a bit unsure about the way you're handling caching. I guess we'll have to keep a close eye on it. Also, have you tested those network closets? And how do you pick the network they connect to?

**Comment by NataKilar** [comment]
> I'll approve, but I'm a bit unsure about the way you're handling caching. I guess we'll have to keep a close eye on it. Also, have you tested those network closets? And how do you pick the network they connect to?

Yes, I've tested the lockers. They don't connect to a network directly, they simply copy the access from a network lock. It's not a perfect system but it's better than a thousand extraneous network devices

**Comment by PsyCommando** [comment]
> > I'll approve, but I'm a bit unsure about the way you're handling caching. I guess we'll have to keep a close eye on it. Also, have you tested those network closets? And how do you pick the network they connect to?
> 
> Yes, I've tested the lockers. They don't connect to a network directly, they simply copy the access from a network lock. It's not a perfect system but it's better than a thousand extraneous network devices

I mean, a thousand might be pushing it. I don't think people would make that many closets? XP

**Pull request merged**
