### PR TITLE
Changes Chems to Standard Baystation Names

### PR DESCRIPTION
**Pull request by Tomsynth1**
## Hello
This is my first ever PR and first time doing DM code so apologies if I violate any rules or miss something.

This PR changes the names of generic chems to their Baystation counterparts and adds a few small changes and details.

List of Chems Altered:

- Oxygel/Oxy_meds - Dexalin
- Stimulants - Hyperzine | SHOULD HAVE BEEN METHYLPHENIDATE | FIXED
- Regenerator/Regenerative Serum - Tricordrazine
- Eyedrops - Imidazoline
- Neuroannealer - Alkysine
- Presyncopics - Cryptobiolin
- Antitoxins - Dylovene
- Sedatives - Soporific
- burn_meds/synthskin - kelotane
- brute_meds/styptic - bicaridine
- painkillers - tramadol
- Stabilizer - Inaprovaline
- Antibiotics - Spaceacillin
- Antiseptic - Sterilizine
- Antirads - Hyronalin
- Amphetamines - Hyperzine
- paralytics - vecuronium_bromide
- retrovirals - ryetalyn
- hallucinogenics - mindbreaker_toxin
- narcotics - impedrezene
- antidepressants - citalopram

## Changelog
:cl:
Rebranded generically-named chems to their names on [Baystation](https://wiki.baystation12.net/Chemistry)
/:cl:

### CODE REVIEW

**Comment by genessee-forgot-his-password-again** [comment]
Looks promising! Did you change the chemical colors to their original baystation counterpart, or just the names?

**Comment by Tomsynth1** [comment]
> Looks promising! Did you change the chemical colors to their original baystation counterpart, or just the names?

Nah they were already the same, I actually used the colours to help figure out which one was which lol. Thanks for the feedback 😁

**Comment by Andrew-Fall** [comment]
This would be something for the upstream [here](https://github.com/NebulaSS13/Nebula)

**Comment by Tomsynth1** [comment]
> This would be something for the upstream [here](https://github.com/NebulaSS13/Nebula)

Upstream is where they replaced the chemical names so that's not really an option, they seem to encourage downstreams to edit stuff like this to their own liking. Is deviating from Neb on these names likely to cause issues?

**Comment by Koollan** [comment]
> This would be something for the upstream [here](https://github.com/NebulaSS13/Nebula)

Yeah, we're going to need to do this downstream unfortunately due to the nature of the chem names being homogenized upstream in the first place, this is where we begin to differ

**Comment by Kurgis** [comment]
~~This is going to cause consistency issues, why not have the names be chosen by config instead of changing all the object paths?~~

**Comment by Kurgis** [comment]
After discussing in the Nebula Discord, you could just create a modpack, re-declare all the objects, and have their names be changed. This creates less future conflicts, and all the medicine names will share with Baystation without needing to change all the object paths.

**Comment by MistakeNot4892** [comment]
The suggested method for doing this to avoid conflicts with upstream when updating would be to put a file of the following kind of thing in a modpack, and include it in your compile:
````
/decl/material/liquid/antidepressant
  name = "citalopram"
````
Stuff that uses a hardcoded chemical name should be fixed upstream to be dynamic.

**Comment by MistakeNot4892** [comment]
Whoops, did not see Kurgis' comment. Will leave mine up for reference.

**Comment by Tomsynth1** [comment]
Thanks for the feedback guys, I'll figure out how to do that and clean up my fork.

**Comment by Tomsynth1** [comment]
Making a new PR as I switched branches.

**Pull request closed without merging**
