### PR TITLE
Adds a Reduced Stock Variant of the Science/Medicine Infini-Vendor

### PR DESCRIPTION
**Pull request by genessee-forgot-his-password-again**
## Description of changes

Adds a 'basic' variant of the science infini-vend that lacks the medicine stock to encourage people to actually make their own medicine, while still giving them access to RND.

Keeps the old 'deluxe' variant for testing purposes.

Also renames it to the 'FrontierTek' because NT isn't a thing out here on the frontier

## Why and what will this PR improve

This will allow players to acquire RND from the infini-vendors without also giving them an infinite amount of medicine to heal their wounds with, which will encourage botany for medicinal uses and chemistry.

## Authorship

genessee did this

## Changelog
:cl:
add: Basic variant of the Science infini-vendor
/:cl:

### CODE REVIEW

**Comment by PsyCommando** [comment]
Just wondering, but you know infini vendors were a open testing thing? They're not in use for outreach.

**Comment by genessee-forgot-his-password-again** [comment]
They're not? I thought the intent was to have the basic vendors for RND supplies and the like for outreach main.

**Comment by PsyCommando** [comment]
> They're not? I thought the intent was to have the basic vendors for RND supplies and the like for outreach main.

The problem is, anyone can just grind those things down into materials and get infinite stuff from those. That's why they're more like dev cheat items.

**Comment by genessee-forgot-his-password-again** [comment]
Oh. Okay, that makes sense. Out of curiosity, though, how are players intended to get the basic RND kit and stuff?

**Review by NataKilar — APPROVED** [review]

**Comment by NataKilar** [comment]
No harm in having it for future use regardless.

**Pull request merged**
