### PR TITLE
7 new softsuit additions.

### PR DESCRIPTION
**Pull request by wasakoki**
this PR adds 7 new/alternative softsuit to the game. That's pretty much it. Below is a preview of the textures ingame.
Untitled

i added these in old persistent SS13 but they never saw any use afaik, so if people are satisfied with these then the sprites are ready to go and are functional ingame, i do have some concerns before being merged though:

~~1. i don't know how RND/manufacturing works so these (probably?) aren't obtainable in-game yet. if someone could clarify and point me to what machine should be making these i would be more than happy to add that to this PR!~~ 
^I added all of the items to textile fab

2. is this where clothing sprites should go? i couldn't really find a spot to put persistent clothing sprites so I just made my own.
3. the 5 job-specific softsuit sprites have modified armor/stat values to (what i think) would best suit the job's role. that being said i was still very liberal with the stats by only making the buffs very minimal (they still are SOFTsuits after all). i'm open to discussing whatever anyone thinks of these stats and changing/removing them if we want that.

## Changelog
:cl:
rscadd: added 7 new softsuits: Engineer, Security, Mining, Medical, Science, alternative generic softsuit, and alternative emergency softsuit.
/:cl:

### CODE REVIEW

**Comment by Tomsynth1** [comment]
I enjoyed these in Quad B, without them the softsuit is bland as hell. I love the one on the right but it's the crappy emergency one lol.

**Comment by VNLoverMay** [comment]
For making them available, you probably want to add them to code/modules/fabrication/designs/textile/space.dm so they're printable in the textile fabricator. That's where the other softsuits are.

**Comment by wasakoki** [comment]
> For making them available, you probably want to add them to code/modules/fabrication/designs/textile/space.dm so they're printable in the textile fabricator. That's where the other softsuits are.

thanks, this looks like the place i was looking for

**Comment by wasakoki** [comment]
ok, I added the softsuits to the textile fabricator & confirmed they are printable. currently they all have the same technology prerequisites & material cost as the generic default softsuit.

PR is ready to be reviewed and merged as long as everything checks out for you all.

**Review by NataKilar — APPROVED** [review]
Everything looks good here.

**Pull request merged**
