### PR TITLE
Upstream merge feb11

### PR DESCRIPTION
**Pull request by PsyCommando**
## Description of changes
Merged in the changes from upstream.

### CODE REVIEW

**Comment by MistakeNot4892** [comment]
Hit me up on Discord if the z-level stuff is unclear - you basically have to make sure any level that exists without calling the z-level incrementing proc has a level data object mapped in (or created) before the unit test runs.

**Comment by PsyCommando** [comment]
> Hit me up on Discord if the z-level stuff is unclear - you basically have to make sure any level that exists without calling the z-level incrementing proc has a level data object mapped in (or created) before the unit test runs.

Alright, thanks!
I think I understand most of it now.

**Comment by PsyCommando** [comment]
Doing some changes upstream, so probably going to have to trash this merge and redo it. We'll see.

**Comment by PsyCommando** [comment]
I'm going to close this, since there's a lot of stuff that has changed.

**Pull request closed without merging**
