### PR TITLE
Chem Name Changes and Additions

### PR DESCRIPTION
**Pull request by Tomsynth1**
## Hello Again
This is version two of PR #159 

I have created a file in the modpack which changes the names of chemicals and some of their containers at compile time, as I understand it. This should mean that the solution is a lot more modular (I think) and will be easier to update while causing less merge conflicts.

List of Chems Altered:

- Oxygel/oxy_meds - dexalin
- Stimulants - methylphenidate
- Regenerator/Regenerative Serum - tricordrazine
- Eyedrops - imidazoline
- Neuroannealer - alkysine
- Antitoxins - dylovene
- Sedatives - soporific
- Burn_meds/synthskin - kelotane REVERTED, see below
- Brute_meds/styptic - bicaridine REVERTED, see below
- Painkillers - tramadol
- Stabilizer - inaprovaline
- Antibiotics - spaceacillin REVERTED
- Antiseptic - sterilizine REVERTED
- Antirads - hyronalin
- Amphetamines - hyperzine
- Paralytics - vecuronium_bromide REVERTED
- Retrovirals - ryetalyn
- Hallucinogenics - mindbreaker_toxin
- Narcotics - impedrezene REVERTED
- Antidepressants - citalopram
- Presyncopics - cryptobiolin
- Gleam - three eye

Chems that were **not** changed:

- psychoactives - space_drugs
- psychotropics - psilocybin
- Antibiotics - spaceacillin
- Antiseptic - sterilizine
- Paralytics - vecuronium_bromide
- Narcotics - impedrezene
- Burn_meds/synthskin - kelotane
- Brute_meds/styptic - bicaridine

I'm on the fence about some of these, including synthskin, stypic and presyncopics as well as the ones that weren't changed. If anyone wants something to stay just drop a comment and I might be willing to change it.

## Update

Reinstated styptic and synthskin as the stock brute and burn chems. Added some new advanced chems with more difficult recipes:

- Bicaridine
- Kelotane
- Dexalin Plus
- Ultra Dexalin
- Paracetamol
- Morphine (Oxycodone)

Looking for advice on whether the recipes are too difficult or easy, keeping in mind that dex+ and oxycodone are a little over double the effectiveness of their stock counterparts. Also not sure whether using radioactive catalysts is sane or not but I read something on the internet about depleted uranium catalysts and that's scientific enough for me.

## Changelog
:cl:
Added a new modpack file which rebrands the names of some chems to their names on [Baystation](https://wiki.baystation12.net/Chemistry)
Added new advanced chems with difficult recipes
/:cl:

### CODE REVIEW

**Comment by genessee-forgot-his-password-again** [comment]
For the most part, I'm in favor of this. However, a couple things I believe should remain the same for the sake of the name being a better indicator of what it does;

Narcotics, Paralytics, Antibiotics, Antiseptic, and Hallucinogenics names should remain the same.

Note that I'm not a coder and my word carry no actual weight with them - you are under no obligation to do as I say. Just making some suggestions.

**Comment by Tomsynth1** [comment]
> For the most part, I'm in favor of this. However, a couple things I believe should remain the same for the sake of the name being a better indicator of what it does;
> 
> Narcotics, Paralytics, Antibiotics, Antiseptic, and Hallucinogenics names should remain the same.
> 
> Note that I'm not a coder and my word carry no actual weight with them - you are under no obligation to do as I say. Just making some suggestions.

I'd agree with all of those except hallucinogenics, since mb toxin kinda suggests that already and it sounds cool. Will revert the others when I get the chance. Thanks for the feedback :)

**Comment by Tomsynth1** [comment]
Reverted those ones, this should be ready to go unless anyone else has a comment.

**Comment by AGasCanister** [comment]
I'd say add Peridaxon back in order to repair decaying organs, or create a chemical that fixes decaying organs instead.

Bicaridine and Kelotane recipes are not difficult to make while Dexalin plus and Oxycodone are near impossible to get, specifically Dexalin Plus which is the most critical one when it comes to saving a life. (Their recipe is also 3:1 which you will get very little quantities)

You could even add Meralyne and Dermaline as the truly hard chems to make that could require platinum, uranium or some ultra hard-to-get chemical if you want, even nanitefluid could be used to add some variety in the recipes (currently it's only used for nanoblood)

**Comment by PipeWizard** [comment]
I recommend to introduce a third tier of chems: bad, normal, and "end game" to solve the dex vs dex+ issue plus it would further deepen gameplay options available.

**Comment by Tomsynth1** [comment]
Nvm a few more changes

**Comment by Tomsynth1** [comment]
Now it's ready for review @NataKilar.

**Review by PipeWizard — DISMISSED** [review]
Tentative approval so that they can begin being tested for balance reasons.  Sooner that slow process starts the better.  It's difficult to determine if something is too easy just from a list standpoint as that doesn't always reflect in game circumstances.

**Review by NataKilar — APPROVED** [review]

**Pull request merged**
